[package]
name = "Liam"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
pest = "2.0"
pest_derive = "2.0"

[[bin]]
name = "liam_vm"
path = "src/rvm/main.rs"

[[bin]]
name = "liamc"
path = "src/liamc/main.rs"