name: Test suite
on: [pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run test
        run: python liamc/tests/runner.py