name: format-action

on:
  pull_request:
      branches:    
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './liamc/src/'
        extensions: 'h,cpp'
        clangFormatVersion: 14.0.0
        style: microsoft