name: WindowsBuild

on:
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ${{github.workspace}}/liamc/build/liamc.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  WIN_BUILD_PATH: bin/win

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.14

    - name: Generate project files
      working-directory: ${{github.workspace}}/liamc
      run: mkdir build && cd build && cmake ..

    - name: Build
      working-directory: ${{github.workspace}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Move binary to release directory
      working-directory: ${{github.workspace}}/liamc
      run: Remove-Item ${{env.WIN_BUILD_PATH}} -Recurse && mkdir ${{env.WIN_BUILD_PATH}} && cp build/Release/liamc.exe ${{env.WIN_BUILD_PATH}}/liamc.exe
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        commit-message: "chore: built windows binaries"
        title: "GH Actions : windows binaries"
        body: "Windows binaries updated and added to bin/win"
